import { Router } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import restaurantsRouter from "./restaurants";
import menuRouter from "./menu";
import cartRouter from "./cart";
import ordersRouter from "./orders";
import reviewsRouter from "./reviews";
import couponsRouter from "./coupons";
import usersRouter from "./users";
import adminRouter from "./admin";
const router = Router();
router.use(healthRouter);
router.use(authRouter);
router.use(restaurantsRouter);
router.use(menuRouter);
router.use(cartRouter);
router.use(ordersRouter);
router.use(reviewsRouter);
router.use(couponsRouter);
router.use(usersRouter);
router.use(adminRouter);
export default router;
